name: rpconda
channels:
  - defaults
dependencies:
  - jupyter
  - pandas
  - python=3.8.12
  - tensorflow-gpu
  - pyqt
  - matplotlib
  - opencv
  - numpy
  - scipy
  - pandas
  - pip
  - pip:
    - keras-tuner
